[style]
based_on_style = google
column_limit = 88
indent_width = 4
split_before_logical_operator = true
dedent_closing_brackets = false
coalesce_brackets = true
blank_line_before_nested_class_or_def = false
spaces_around_default_or_named_assign = true


; [style]
; based_on_style = pep8
; column_limit = 100
; indent_width = 4
; spaces_before_comment = 2
; split_before_logical_operator = true



; [style]
; based_on_style = pep8
; column_limit = 88
; indent_width = 4
